echo : dummy"
sudo: required
services:
- docker
language: ruby
before_install:
- sudo docker build -t quine-relay .
script:
- sudo docker run --privileged --name qr -t quine-relay
after_success:
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && sh .travis.yml
env:
  global:
    secure: NGDakAqRZgGJwEJTlXenhoXcq9ulf0X0fjnC+oF+ktTXCRpdbQd8+faxIW5DR26qF5OMWPqsLtUv8HtQyv5P5gVNs41hXygmNU1R9TOMpw64FjXtkD1HNf0D4jE2STuUU2xB+sCifeb9z6SvMpcy6ZswBlhAVnV+5dboNZL0Ww0=
dummy: |
  dummy" > /dev/null
  mkdir spoiler
  sudo docker cp qr:/usr/local/share/quine-relay/QR.rb spoiler/
  sudo docker cp qr:/usr/local/share/quine-relay/QR.scala spoiler/
  sudo docker cp qr:/usr/local/share/quine-relay/QR.scm spoiler/
  sudo docker cp qr:/usr/local/share/quine-relay/QR.sci spoiler/
  sudo docker cp qr:/usr/local/share/quine-relay/QR.bash spoiler/
  sudo docker cp qr:/usr/local/share/quine-relay/QR.sl spoiler/
  sudo docker cp qr:/usr/local/share/quine-relay/QR.st spoiler/
  sudo docker cp qr:/usr/local/share/quine-relay/QR.spl spoiler/
  sudo docker cp qr:/usr/local/share/quine-relay/QR.sml spoiler/
  sudo docker cp qr:/usr/local/share/quine-relay/QR.sq spoiler/
  sudo docker cp qr:/usr/local/share/quine-relay/QR.tcl spoiler/
  sudo docker cp qr:/usr/local/share/quine-relay/QR.t spoiler/
  sudo docker cp qr:/usr/local/share/quine-relay/QR.unl spoiler/
  sudo docker cp qr:/usr/local/share/quine-relay/QR.vala spoiler/
  sudo docker cp qr:/usr/local/share/quine-relay/QR.v spoiler/
  sudo docker cp qr:/usr/local/share/quine-relay/QR.vb spoiler/
  sudo docker cp qr:/usr/local/share/quine-relay/QR.ws spoiler/
  sudo docker cp qr:/usr/local/share/quine-relay/QR.xslt spoiler/
  sudo docker cp qr:/usr/local/share/quine-relay/QR.yorick spoiler/
  sudo docker cp qr:/usr/local/share/quine-relay/QR.azm spoiler/
  sudo docker cp qr:/usr/local/share/quine-relay/QR.+ spoiler/
  sudo docker cp qr:/usr/local/share/quine-relay/qr.adb spoiler/
  sudo docker cp qr:/usr/local/share/quine-relay/QR.als spoiler/
  sudo docker cp qr:/usr/local/share/quine-relay/QR.a68 spoiler/
  sudo docker cp qr:/usr/local/share/quine-relay/QR.ante spoiler/
  sudo docker cp qr:/usr/local/share/quine-relay/QR.asy spoiler/
  sudo docker cp qr:/usr/local/share/quine-relay/QR.dats spoiler/
  sudo docker cp qr:/usr/local/share/quine-relay/QR.awk spoiler/
  sudo docker cp qr:/usr/local/share/quine-relay/QR.bc spoiler/
  sudo docker cp qr:/usr/local/share/quine-relay/QR.bef spoiler/
  sudo docker cp qr:/usr/local/share/quine-relay/QR.Blc spoiler/
  sudo docker cp qr:/usr/local/share/quine-relay/QR.bf spoiler/
  sudo docker cp qr:/usr/local/share/quine-relay/QR.c spoiler/
  sudo docker cp qr:/usr/local/share/quine-relay/QR.cpp spoiler/
  sudo docker cp qr:/usr/local/share/quine-relay/QR.cs spoiler/
  sudo docker cp qr:/usr/local/share/quine-relay/QR.cd spoiler/
  sudo docker cp qr:/usr/local/share/quine-relay/QR.chef spoiler/
  sudo docker cp qr:/usr/local/share/quine-relay/QR.clj spoiler/
  sudo docker cp qr:/usr/local/share/quine-relay/QR.cob spoiler/
  sudo docker cp qr:/usr/local/share/quine-relay/QR.coffee spoiler/
  sudo docker cp qr:/usr/local/share/quine-relay/QR.lisp spoiler/
  sudo docker cp qr:/usr/local/share/quine-relay/QR.d spoiler/
  sudo docker cp qr:/usr/local/share/quine-relay/QR.dc spoiler/
  sudo docker cp qr:/usr/local/share/quine-relay/QR.ec spoiler/
  sudo docker cp qr:/usr/local/share/quine-relay/QR.exs spoiler/
  sudo docker cp qr:/usr/local/share/quine-relay/QR.el spoiler/
  sudo docker cp qr:/usr/local/share/quine-relay/QR.erl spoiler/
  sudo docker cp qr:/usr/local/share/quine-relay/QR.fsx spoiler/
  sudo docker cp qr:/usr/local/share/quine-relay/QR.false spoiler/
  sudo docker cp qr:/usr/local/share/quine-relay/QR.fs spoiler/
  sudo docker cp qr:/usr/local/share/quine-relay/QR.f spoiler/
  sudo docker cp qr:/usr/local/share/quine-relay/QR.f90 spoiler/
  sudo docker cp qr:/usr/local/share/quine-relay/QR.gbs spoiler/
  sudo docker cp qr:/usr/local/share/quine-relay/QR.g spoiler/
  sudo docker cp qr:/usr/local/share/quine-relay/QR.gel spoiler/
  sudo docker cp qr:/usr/local/share/quine-relay/QR.plt spoiler/
  sudo docker cp qr:/usr/local/share/quine-relay/QR.go spoiler/
  sudo docker cp qr:/usr/local/share/quine-relay/QR.gpt spoiler/
  sudo docker cp qr:/usr/local/share/quine-relay/QR.gri spoiler/
  sudo docker cp qr:/usr/local/share/quine-relay/QR.groovy spoiler/
  sudo docker cp qr:/usr/local/share/quine-relay/QR.hs spoiler/
  sudo docker cp qr:/usr/local/share/quine-relay/QR.hx spoiler/
  sudo docker cp qr:/usr/local/share/quine-relay/QR.icn spoiler/
  sudo docker cp qr:/usr/local/share/quine-relay/QR.i spoiler/
  sudo docker cp qr:/usr/local/share/quine-relay/QR.j spoiler/
  sudo docker cp qr:/usr/local/share/quine-relay/QR.java spoiler/
  sudo docker cp qr:/usr/local/share/quine-relay/QR.js spoiler/
  sudo docker cp qr:/usr/local/share/quine-relay/QR.jq spoiler/
  sudo docker cp qr:/usr/local/share/quine-relay/QR.jl spoiler/
  sudo docker cp qr:/usr/local/share/quine-relay/QR.lazy spoiler/
  sudo docker cp qr:/usr/local/share/quine-relay/qr.li spoiler/
  sudo docker cp qr:/usr/local/share/quine-relay/QR.ll spoiler/
  sudo docker cp qr:/usr/local/share/quine-relay/QR.logo spoiler/
  sudo docker cp qr:/usr/local/share/quine-relay/QR.lol spoiler/
  sudo docker cp qr:/usr/local/share/quine-relay/QR.lua spoiler/
  sudo docker cp qr:/usr/local/share/quine-relay/QR.mk spoiler/
  sudo docker cp qr:/usr/local/share/quine-relay/QR.mac spoiler/
  sudo docker cp qr:/usr/local/share/quine-relay/QR.il spoiler/
  sudo docker cp qr:/usr/local/share/quine-relay/QR.asm spoiler/
  sudo docker cp qr:/usr/local/share/quine-relay/QR.neko spoiler/
  sudo docker cp qr:/usr/local/share/quine-relay/QR.5c spoiler/
  sudo docker cp qr:/usr/local/share/quine-relay/QR.nim spoiler/
  sudo docker cp qr:/usr/local/share/quine-relay/QR.m spoiler/
  sudo docker cp qr:/usr/local/share/quine-relay/QR.ml spoiler/
  sudo docker cp qr:/usr/local/share/quine-relay/QR.octave spoiler/
  sudo docker cp qr:/usr/local/share/quine-relay/QR.ook spoiler/
  sudo docker cp qr:/usr/local/share/quine-relay/QR.gp spoiler/
  sudo docker cp qr:/usr/local/share/quine-relay/QR.pasm spoiler/
  sudo docker cp qr:/usr/local/share/quine-relay/QR.pas spoiler/
  sudo docker cp qr:/usr/local/share/quine-relay/QR.pl spoiler/
  sudo docker cp qr:/usr/local/share/quine-relay/QR.php spoiler/
  sudo docker cp qr:/usr/local/share/quine-relay/QR.png spoiler/
  sudo docker cp qr:/usr/local/share/quine-relay/QR.pike spoiler/
  sudo docker cp qr:/usr/local/share/quine-relay/QR.ps spoiler/
  sudo docker cp qr:/usr/local/share/quine-relay/QR.ppt spoiler/
  sudo docker cp qr:/usr/local/share/quine-relay/QR.prolog spoiler/
  sudo docker cp qr:/usr/local/share/quine-relay/QR.py spoiler/
  sudo docker cp qr:/usr/local/share/quine-relay/QR.R spoiler/
  sudo docker cp qr:/usr/local/share/quine-relay/QR.ratfor spoiler/
  sudo docker cp qr:/usr/local/share/quine-relay/QR.rexx spoiler/
  cd spoiler
  git init --quiet
  git config user.name 'Yusuke Endoh'
  git config user.email 'mame@ruby-lang.org'
  git add .
  git commit -m spoiler --quiet
  git push --force --quiet "https://${GH_TOKEN}@github.com/mame/quine-relay" master:spoiler
  echo The intermediate sources are available: https://github.com/mame/quine-relay/tree/spoiler
